services:
  mysql-service:
    image: mysql:latest
    restart: always
    container_name: mysql-service
    environment:
      MYSQL_ROOT_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge