services:
  eureka-service:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - my-network

  authorization-service:
    build:
      context: ./authorization-service
      dockerfile: Dockerfile
    container_name: authorization-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - mysql-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    networks:
      - my-network

  mysql-service:
    image: mysql:latest
    restart: always
    container_name: pet-mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
