version: '3.8'

services:
  mysql-service:
    image: mysql:latest
    restart: always
    container_name: pet-mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  mysql-shop:
    image: mysql:latest
    restart: always
    container_name: mysql-shop-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_shop_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql_data:
  mysql_shop_data:

networks:
  my-network:
    driver: bridge
