server:
  port: 8080

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: authorization-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3307/authdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-id: "secret"
            client-secret: "secret"
          github:
            client-id: "secret"
            client-secret: "secret"