spring:
  application:
    name: authorization-service
  profiles:
    active: docker

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      authorization-server:
        issuer: http://127.0.0.1:9090
    user:
      name: user
      password: password
      client:
        registration:
          google:
            client-id: "secret"
            client-secret: "secret"
          github:
            client-id: "secret"
            client-secret: "secret"


logging:
  level:
    org.springframework.security: trace
server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/authdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql-service:3306/authdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/






