spring:
  profiles:
    active: docker

  application:
    name: authorization-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            client-id: "secret"
            client-secret: "secret"
          github:
            client-id: "secret"
            client-secret: "secret"
      authorizationserver:
        issuer: http://127.0.0.1:8080


logging:
  level:
    org.springframework.security: trace
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/authdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: docker


  datasource:
    url: jdbc:mysql://mysql-service:3306/authdb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/






